<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [Twisted-Python] poll reactor question
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:twisted-python%40twistedmatrix.com?Subject=%5BTwisted-Python%5D%20poll%20reactor%20question&In-Reply-To=">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="014640.html">
   <LINK REL="Next"  HREF="014642.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[Twisted-Python] poll reactor question</H1>
    <B>Christopher Zorn</B> 
    <A HREF="mailto:twisted-python%40twistedmatrix.com?Subject=%5BTwisted-Python%5D%20poll%20reactor%20question&In-Reply-To="
       TITLE="[Twisted-Python] poll reactor question">christopher.zorn at gmail.com
       </A><BR>
    <I>Sun Jan 14 11:26:35 EST 2007</I>
    <P><UL>
        <LI>Previous message: <A HREF="014640.html">[Twisted-Python] client,	deferred and/or reactor hung on these 2 URL's
</A></li>
        <LI>Next message: <A HREF="014642.html">[Twisted-Python] poll reactor question
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#14639">[ date ]</a>
              <a href="thread.html#14639">[ thread ]</a>
              <a href="subject.html#14639">[ subject ]</a>
              <a href="author.html#14639">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>Hello,

When I use the poll reactor I get the following traceback every now and then :

 Traceback (most recent call last):
          File &quot;/usr/lib/python2.3/site-packages/twisted/application/app.py&quot;,
line 278, in run
            runApp(config)
          File &quot;/usr/lib/python2.3/site-packages/twisted/scripts/twistd.py&quot;,
line 197, in runApp
            app.runReactorWithLogging(config, oldstdout, oldstderr)
          File &quot;/usr/lib/python2.3/site-packages/twisted/application/app.py&quot;,
line 131, in runReactorWithLogging
            reactor.run()
          File &quot;/usr/lib/python2.3/site-packages/twisted/internet/posixbase.py&quot;,
line 218, in run
            self.mainLoop()
        --- &lt;exception caught here&gt; ---
          File &quot;/usr/lib/python2.3/site-packages/twisted/internet/posixbase.py&quot;,
line 229, in mainLoop
            self.doIteration(t)
          File &quot;/usr/lib/python2.3/site-packages/twisted/internet/pollreactor.py&quot;,
line 141, in doPoll
            for fd, event in l:
        exceptions.OverflowError: long int too large to convert to int


I looked in the tickets and could not find this. I am using twisted
2.4.0 and as you can see, python 2.3

Does anyone know what this could be? It only happens with this reactor.


</PRE>

<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="014640.html">[Twisted-Python] client,	deferred and/or reactor hung on these 2 URL's
</A></li>
	<LI>Next message: <A HREF="014642.html">[Twisted-Python] poll reactor question
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#14639">[ date ]</a>
              <a href="thread.html#14639">[ thread ]</a>
              <a href="subject.html#14639">[ subject ]</a>
              <a href="author.html#14639">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="http://twistedmatrix.com/cgi-bin/mailman/listinfo/twisted-python">More information about the Twisted-Python
mailing list</a><br>
</body></html>
