<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [Twisted-Python] Twisted plugins and py2exe
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:twisted-python%40twistedmatrix.com?Subject=%5BTwisted-Python%5D%20Twisted%20plugins%20and%20py2exe&In-Reply-To=49A3D0A9.3040209%40arimaz.com">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="019244.html">
   <LINK REL="Next"  HREF="019246.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[Twisted-Python] Twisted plugins and py2exe</H1>
    <B>Jean-Paul Calderone</B> 
    <A HREF="mailto:twisted-python%40twistedmatrix.com?Subject=%5BTwisted-Python%5D%20Twisted%20plugins%20and%20py2exe&In-Reply-To=49A3D0A9.3040209%40arimaz.com"
       TITLE="[Twisted-Python] Twisted plugins and py2exe">exarkun at divmod.com
       </A><BR>
    <I>Tue Feb 24 10:15:18 EST 2009</I>
    <P><UL>
        <LI>Previous message: <A HREF="019244.html">[Twisted-Python] Twisted plugins and py2exe
</A></li>
        <LI>Next message: <A HREF="019246.html">[Twisted-Python] Twisted plugins and py2exe
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#19245">[ date ]</a>
              <a href="thread.html#19245">[ thread ]</a>
              <a href="subject.html#19245">[ subject ]</a>
              <a href="author.html#19245">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>On Tue, 24 Feb 2009 11:49:13 +0100, Gabriel Rossetti &lt;<A HREF="http://twistedmatrix.com/cgi-bin/mailman/listinfo/twisted-python">gabriel.rossetti at arimaz.com</A>&gt; wrote:
&gt;<i>Hello everyone!
</I>&gt;<i>
</I>&gt;<i>I used py2exe on a Twisted app of mine and I get this exception :
</I>&gt;<i>
</I>&gt;<i>
</I>&gt;<i>Traceback (most recent call last):
</I>&gt;<i>  File &quot;proj\service.pyc&quot;, line 1308, in connectionMade
</I>&gt;<i>
</I>&gt;<i>  File &quot;proj\service.pyc&quot;, line 1640, in _register
</I>&gt;<i>
</I>&gt;<i>  File &quot;proj\service.pyc&quot;, line 504, in loadPlugins
</I>&gt;<i>
</I>&gt;<i>  File &quot;twisted\plugin.pyc&quot;, line 200, in getPlugins
</I>&gt;<i>
</I>&gt;<i>--- &lt;exception caught here&gt; ---
</I>&gt;<i>  File &quot;twisted\plugin.pyc&quot;, line 179, in getCache
</I>&gt;<i>
</I>&gt;<i>exceptions.AttributeError: ZipPath instance has no attribute 'setContent'
</I>&gt;<i>
</I>&gt;<i>Has anyone ever had this problem while using plugins with Twisted and 
</I>&gt;<i>py2exe?
</I>
No, but from the traceback, it seems fairly clear that the plugin system
is trying to write a plugin cache file into your py2exe-created zip file
of Python source.  This won't work, of course.  You could try making sure
the cache file is up to date and including it in the zip file, but I have
no idea if this will actually produce sensible behavior.  The other
possibility is to actually teach the plugin system about zip files (ie,
contribute a patch to Twisted to support this case).

Jean-Paul


</PRE>

<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="019244.html">[Twisted-Python] Twisted plugins and py2exe
</A></li>
	<LI>Next message: <A HREF="019246.html">[Twisted-Python] Twisted plugins and py2exe
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#19245">[ date ]</a>
              <a href="thread.html#19245">[ thread ]</a>
              <a href="subject.html#19245">[ subject ]</a>
              <a href="author.html#19245">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="http://twistedmatrix.com/cgi-bin/mailman/listinfo/twisted-python">More information about the Twisted-Python
mailing list</a><br>
</body></html>
