<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
 <HEAD>
   <TITLE> [Twisted-Python] misleading error in twisted.enterprise.adbapi
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:twisted-python%40twistedmatrix.com?Subject=Re%3A%20%5BTwisted-Python%5D%20misleading%20error%20in%20twisted.enterprise.adbapi&In-Reply-To=%3C012701ca2826%24dddce4f0%249996aed0%24%40com%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <style type="text/css">
       pre {
           white-space: pre-wrap;       /* css-2.1, curent FF, Opera, Safari */
           }
   </style>
   <META http-equiv="Content-Type" content="text/html; charset=utf-8">
   <LINK REL="Previous"  HREF="052827.html">
   <LINK REL="Next"  HREF="052813.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[Twisted-Python] misleading error in twisted.enterprise.adbapi</H1>
    <B>Alec Matusis</B> 
    <A HREF="mailto:twisted-python%40twistedmatrix.com?Subject=Re%3A%20%5BTwisted-Python%5D%20misleading%20error%20in%20twisted.enterprise.adbapi&In-Reply-To=%3C012701ca2826%24dddce4f0%249996aed0%24%40com%3E"
       TITLE="[Twisted-Python] misleading error in twisted.enterprise.adbapi">matusis at yahoo.com
       </A><BR>
    <I>Fri Aug 28 15:31:12 MDT 2009</I>
    <P><UL>
        <LI>Previous message (by thread): <A HREF="052827.html">[Twisted-Python] Some way for Trial to allow selective running	of tests?
</A></li>
        <LI>Next message (by thread): <A HREF="052813.html">[Twisted-Python] Some way for Trial to allow selective running	of tests?
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#52828">[ date ]</a>
              <a href="thread.html#52828">[ thread ]</a>
              <a href="subject.html#52828">[ subject ]</a>
              <a href="author.html#52828">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>
We are using twisted.enterprise.adbapi for connecting to MySQL.
In one of our large tables, the primary key reached its maximum value of
2147483647, and INSERTs became impossible.

When I executed the same INSERT from mysql command line manually, it gave:

ERROR 1062 (23000): Duplicate entry '2147483647' for key 1

In twisted logs however, for the same INSERT the error was much less
specific:

2014, &quot;Commands out of sync; you can't run this command now&quot;

I am concerned about this, since this 2014 error has appeared before in the
twisted logs, in many completely different contexts. Can you shed any light
on why we do not get the specific 1062 error, and what this 2014, &quot;Commands
out of sync; you can't run this command now&quot; is about?




</PRE>

<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message (by thread): <A HREF="052827.html">[Twisted-Python] Some way for Trial to allow selective running	of tests?
</A></li>
	<LI>Next message (by thread): <A HREF="052813.html">[Twisted-Python] Some way for Trial to allow selective running	of tests?
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#52828">[ date ]</a>
              <a href="thread.html#52828">[ thread ]</a>
              <a href="subject.html#52828">[ subject ]</a>
              <a href="author.html#52828">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="https://twistedmatrix.com/cgi-bin/mailman/listinfo/twisted-python">More information about the Twisted-Python
mailing list</a><br>
</body></html>
