<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
 <HEAD>
   <TITLE> [Twisted-Python] Deferred question
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:twisted-python%40twistedmatrix.com?Subject=Re%3A%20%5BTwisted-Python%5D%20Deferred%20question&In-Reply-To=%3C493CE88D.3070507%40arimaz.com%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <style type="text/css">
       pre {
           white-space: pre-wrap;       /* css-2.1, curent FF, Opera, Safari */
           }
   </style>
   <META http-equiv="Content-Type" content="text/html; charset=utf-8">
   <LINK REL="Previous"  HREF="051435.html">
   <LINK REL="Next"  HREF="051335.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[Twisted-Python] Deferred question</H1>
    <B>Gabriel Rossetti</B> 
    <A HREF="mailto:twisted-python%40twistedmatrix.com?Subject=Re%3A%20%5BTwisted-Python%5D%20Deferred%20question&In-Reply-To=%3C493CE88D.3070507%40arimaz.com%3E"
       TITLE="[Twisted-Python] Deferred question">gabriel.rossetti at arimaz.com
       </A><BR>
    <I>Mon Dec  8 02:27:41 MST 2008</I>
    <P><UL>
        <LI>Previous message (by thread): <A HREF="051435.html">[Twisted-Python] Weekly Bug Summary
</A></li>
        <LI>Next message (by thread): <A HREF="051335.html">[Twisted-Python] Deferred question
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#51329">[ date ]</a>
              <a href="thread.html#51329">[ thread ]</a>
              <a href="subject.html#51329">[ subject ]</a>
              <a href="author.html#51329">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>Hello everyone,

I have a question concerning defers, I have a service that needs to 
query IO until it answers. The IO can be disconnected, connected but 
off, connected and on; depending on the state I get different 
exceptions. I wrote something like :

def __requestId(self, _):
        d = self.callPlugin(PLUGIN_NAME)
        d.addCallback(self.__receivedAns)
        d.addErrback(self.__requestId)

The plugin makes the request in a thread and the deferred is returned 
and called when either an answer is received or am exception is raised 
(e.g. timeout, missing hardware, etc)

This seams to work well, except that when I let the system run for a 
long time without the hardware being present or off (several hours/days) 
the memory consumption goes way up. I don' t really know what is causing 
this, and I'm looking for possible reasons, so I was wondering if maybe 
this could be what is causing the problem. It's probably not that, 
because from what I understand it works like this :

   1. the first request is made
   2. there is a timeout or something that raises the exception
   3. the errback gets called
   4. it makes a new request
   5. the deferred gets garbage collected
   6. the new request follows the same path

Can anyone confirm that this is correct, or are my defers somehow 
staying alive and not being garbage collected?

Thank you,
Gabriel Rossetti


</PRE>

<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message (by thread): <A HREF="051435.html">[Twisted-Python] Weekly Bug Summary
</A></li>
	<LI>Next message (by thread): <A HREF="051335.html">[Twisted-Python] Deferred question
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#51329">[ date ]</a>
              <a href="thread.html#51329">[ thread ]</a>
              <a href="subject.html#51329">[ subject ]</a>
              <a href="author.html#51329">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="https://twistedmatrix.com/cgi-bin/mailman/listinfo/twisted-python">More information about the Twisted-Python
mailing list</a><br>
</body></html>
