<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [Twisted-Python] Passing extra arguments along callbacks
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:twisted-python%40twistedmatrix.com?Subject=%5BTwisted-Python%5D%20Passing%20extra%20arguments%20along%20callbacks&In-Reply-To=">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="024690.html">
   <LINK REL="Next"  HREF="024692.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[Twisted-Python] Passing extra arguments along callbacks</H1>
    <B>Terry Jones</B> 
    <A HREF="mailto:twisted-python%40twistedmatrix.com?Subject=%5BTwisted-Python%5D%20Passing%20extra%20arguments%20along%20callbacks&In-Reply-To="
       TITLE="[Twisted-Python] Passing extra arguments along callbacks">terry at jon.es
       </A><BR>
    <I>Fri Oct 21 21:50:56 EDT 2011</I>
    <P><UL>
        <LI>Previous message: <A HREF="024690.html">[Twisted-Python] Passing extra arguments along callbacks
</A></li>
        <LI>Next message: <A HREF="024692.html">[Twisted-Python] Passing extra arguments along callbacks
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#24691">[ date ]</a>
              <a href="thread.html#24691">[ thread ]</a>
              <a href="subject.html#24691">[ subject ]</a>
              <a href="author.html#24691">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>Hi Jonathan

&gt;<i> def resolve(ip):
</I>&gt;<i>     ptr = '.'.join(ip.split('.')[::-1]) + '.in-addr.arpa'
</I>&gt;<i>     return client.lookupPointer(ptr).\
</I>&gt;<i>             addCallback(lambda x: (ip, x)).\
</I>&gt;<i>             addErrback(lambda x: (ip, x))
</I>
Your errback isn't raising and isn't returning a Failure, so the processing
switches back to the callback chain. If you add an errback that's a real
function and it raises something, things will work. E.g.

def err(fail, ip):
    raise Exception(fail, ip)

return client.lookupPointer(ptr).\
    addCallback(lambda x: (ip, x)).\
    addErrback(err, ip)


&gt;<i> l = [resolve(ip) for ip in IPS]
</I>&gt;<i> d = DeferredList( l, consumeErrors=True).\
</I>&gt;<i>         addCallback(display_results).\
</I>&gt;<i>         addCallback(lambda x: reactor.stop)
</I>
Try reactor.stop()

Terry

</PRE>





<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="024690.html">[Twisted-Python] Passing extra arguments along callbacks
</A></li>
	<LI>Next message: <A HREF="024692.html">[Twisted-Python] Passing extra arguments along callbacks
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#24691">[ date ]</a>
              <a href="thread.html#24691">[ thread ]</a>
              <a href="subject.html#24691">[ subject ]</a>
              <a href="author.html#24691">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="http://twistedmatrix.com/cgi-bin/mailman/listinfo/twisted-python">More information about the Twisted-Python
mailing list</a><br>
</body></html>
