<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
 <HEAD>
   <TITLE> [Twisted-Python] Catching error in	protocol.ReconnectingClientFactory
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:twisted-python%40twistedmatrix.com?Subject=Re%3A%20%5BTwisted-Python%5D%20Catching%20error%20in%0A%09protocol.ReconnectingClientFactory&In-Reply-To=%3C4FE8569E.3090504%40webscio.net%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <style type="text/css">
       pre {
           white-space: pre-wrap;       /* css-2.1, curent FF, Opera, Safari */
           }
   </style>
   <META http-equiv="Content-Type" content="text/html; charset=utf-8">
   <LINK REL="Previous"  HREF="058114.html">
   <LINK REL="Next"  HREF="058170.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[Twisted-Python] Catching error in	protocol.ReconnectingClientFactory</H1>
    <B>Martin</B> 
    <A HREF="mailto:twisted-python%40twistedmatrix.com?Subject=Re%3A%20%5BTwisted-Python%5D%20Catching%20error%20in%0A%09protocol.ReconnectingClientFactory&In-Reply-To=%3C4FE8569E.3090504%40webscio.net%3E"
       TITLE="[Twisted-Python] Catching error in	protocol.ReconnectingClientFactory">martin at webscio.net
       </A><BR>
    <I>Mon Jun 25 06:16:30 MDT 2012</I>
    <P><UL>
        <LI>Previous message (by thread): <A HREF="058114.html">[Twisted-Python] Catching error in	protocol.ReconnectingClientFactory
</A></li>
        <LI>Next message (by thread): <A HREF="058170.html">[Twisted-Python] Catching error in	protocol.ReconnectingClientFactory
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#58168">[ date ]</a>
              <a href="thread.html#58168">[ thread ]</a>
              <a href="subject.html#58168">[ subject ]</a>
              <a href="author.html#58168">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>On 14/06/12 12:38, Martin wrote:
&gt;<i> Hi, thanks for your reply.
</I>&gt;<i>
</I>&gt;<i> Indeed, the ReconnectingClientFactory is being sent the Failure object to
</I>&gt;<i>
</I>&gt;<i> def clientConnectionLost(self, connector, reason):
</I>&gt;<i>         log.msg('Lost connection. Reason: %s' % reason)
</I>&gt;<i> protocol.ReconnectingClientFactory.clientConnectionLost(self, 
</I>&gt;<i> connector, reason)
</I>&gt;<i>
</I>&gt;<i> where &quot;reason&quot; is the Failure object that is &quot;unhandled&quot;. is there 
</I>&gt;<i> anything I could do to it there to make it handled?
</I>&gt;<i>
</I>&gt;<i> Also, the documentation in 
</I>&gt;<i> <A HREF="http://twistedmatrix.com/documents/current/core/howto/defer.html">http://twistedmatrix.com/documents/current/core/howto/defer.html</A> says 
</I>&gt;<i> that one can do d.addErrback(err.log) to deal with unhandled errors, 
</I>&gt;<i> but what is d?
</I>&gt;<i>
</I>&gt;<i> In general, I'm not doing anything special.. I'm creating a 
</I>&gt;<i> ReconnectingClientFactory and connecting it to a server..
</I>&gt;<i> f = MyReconnectingClientFactory(..)
</I>&gt;<i> reactor.connectSSL(url, port, f, ssl.ClientContextFactory())
</I>&gt;<i> reactor.run()
</I>&gt;<i>
</I>&gt;<i> Basically it. Any thoughts? Thanks a lot!
</I>&gt;&gt;<i> On Jun 11, 2012, at 8:01 AM, Martin wrote:
</I>&gt;&gt;<i>
</I>&gt;&gt;&gt;<i> Hi there,
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i> I've been looking around for a solution for several hours now, and 
</I>&gt;&gt;&gt;<i> maybe
</I>&gt;&gt;&gt;<i> I'm just missing something..
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i> I've a factory that implements protocol.ReconnectingClientFactory which
</I>&gt;&gt;&gt;<i> works just fine, however, whenever the program ends running, I get a
</I>&gt;&gt;&gt;<i> bunch of Unhandled error in Deferred messages in my log for each
</I>&gt;&gt;&gt;<i> disconnection that occurred during runtime, such as Failure:
</I>&gt;&gt;&gt;<i> twisted.internet.error.ConnectionLost: ...
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i> Is there any way I could somehow &quot;handle&quot; these during runtime, so that
</I>&gt;&gt;&gt;<i> my log wouldn't be spammed with this at the end.. (or avoid it being
</I>&gt;&gt;&gt;<i> spammed somehow..)
</I>&gt;&gt;<i> These messages are coming from some code which is issuing Deferreds, 
</I>&gt;&gt;<i> not from ReconnectingClientFactory.  You need to add an errback to 
</I>&gt;&gt;<i> those Deferreds in your application code.  There's no way to write a 
</I>&gt;&gt;<i> catch-all, just like there's no way to write a catch-all that can 
</I>&gt;&gt;<i> stop exceptions from being raised in basic Python.
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> I can't say more without a code example, preferably 
</I>&gt;&gt;<i> a&lt;<A HREF="http://sscce.org/">http://sscce.org/</A>&gt;.
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> -glyph
</I>&gt;&gt;<i>
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> _______________________________________________
</I>&gt;&gt;<i> Twisted-Python mailing list
</I>&gt;&gt;<i> <A HREF="https://twistedmatrix.com/cgi-bin/mailman/listinfo/twisted-python">Twisted-Python at twistedmatrix.com</A>
</I>&gt;&gt;<i> <A HREF="http://twistedmatrix.com/cgi-bin/mailman/listinfo/twisted-python">http://twistedmatrix.com/cgi-bin/mailman/listinfo/twisted-python</A>
</I>&gt;&gt;<i>
</I>&gt;&gt;<i>
</I>&gt;<i>
</I>No suggestions as to how I could get rid of this? :(



</PRE>

<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message (by thread): <A HREF="058114.html">[Twisted-Python] Catching error in	protocol.ReconnectingClientFactory
</A></li>
	<LI>Next message (by thread): <A HREF="058170.html">[Twisted-Python] Catching error in	protocol.ReconnectingClientFactory
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#58168">[ date ]</a>
              <a href="thread.html#58168">[ thread ]</a>
              <a href="subject.html#58168">[ subject ]</a>
              <a href="author.html#58168">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="https://twistedmatrix.com/cgi-bin/mailman/listinfo/twisted-python">More information about the Twisted-Python
mailing list</a><br>
</body></html>
