<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
 <HEAD>
   <TITLE> [Twisted-Python] If the errbacks of a canceled Deferred are called with error other than CancelledError, is this acceptable?
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:twisted-python%40twistedmatrix.com?Subject=Re%3A%20%5BTwisted-Python%5D%20If%20the%20errbacks%20of%20a%20canceled%20Deferred%20are%0A%20called%20with%20error%20other%20than%20CancelledError%2C%20is%20this%20acceptable%3F&In-Reply-To=%3CCAPkRfUSYXqvNsTq%3DoXGUb9TAeDgpyaCcmcHPZPo6saUNhsJ8mQ%40mail.gmail.com%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <style type="text/css">
       pre {
           white-space: pre-wrap;       /* css-2.1, curent FF, Opera, Safari */
           }
   </style>
   <META http-equiv="Content-Type" content="text/html; charset=utf-8">
   <LINK REL="Previous"  HREF="059564.html">
   <LINK REL="Next"  HREF="059568.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[Twisted-Python] If the errbacks of a canceled Deferred are called with error other than CancelledError, is this acceptable?</H1>
    <B>Christopher Armstrong</B> 
    <A HREF="mailto:twisted-python%40twistedmatrix.com?Subject=Re%3A%20%5BTwisted-Python%5D%20If%20the%20errbacks%20of%20a%20canceled%20Deferred%20are%0A%20called%20with%20error%20other%20than%20CancelledError%2C%20is%20this%20acceptable%3F&In-Reply-To=%3CCAPkRfUSYXqvNsTq%3DoXGUb9TAeDgpyaCcmcHPZPo6saUNhsJ8mQ%40mail.gmail.com%3E"
       TITLE="[Twisted-Python] If the errbacks of a canceled Deferred are called with error other than CancelledError, is this acceptable?">radix at twistedmatrix.com
       </A><BR>
    <I>Tue Jun 18 09:42:50 MDT 2013</I>
    <P><UL>
        <LI>Previous message (by thread): <A HREF="059564.html">[Twisted-Python] If the errbacks of a canceled Deferred are called with error other than CancelledError, is this acceptable?
</A></li>
        <LI>Next message (by thread): <A HREF="059568.html">[Twisted-Python] If the errbacks of a canceled Deferred are	called with error other than CancelledError, is this acceptable?
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#59566">[ date ]</a>
              <a href="thread.html#59566">[ thread ]</a>
              <a href="subject.html#59566">[ subject ]</a>
              <a href="author.html#59566">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>On Tue, Jun 18, 2013 at 8:37 AM, Itamar Turner-Trauring &lt;
<A HREF="https://twistedmatrix.com/cgi-bin/mailman/listinfo/twisted-python">itamar at futurefoundries.com</A>&gt; wrote:

&gt;<i> By way of background, Kai Zhang is one of our GSoC interns, working on
</I>&gt;<i> adding Deferred cancellation support to Twisted. I believe the specific
</I>&gt;<i> module he is working on is the POP3 client, but it's a general question -
</I>&gt;<i> should we try to keep CancelledError percolating all the way to the top of
</I>&gt;<i> callback chain when possible? My first thought is &quot;yes&quot; since that's a more
</I>&gt;<i> informative reason, but maybe someone else has a counter-argument
</I>&gt;<i>
</I>
I definitely think the error should explain that cancellation occurred; I
can also imagine cases where you'd want to know the specifics of how that
cancellation occurred, or how far some operation got before the
cancellation was executed (especially if we're talking about mutating
operations). ConnectionDone definitely doesn't sound good.

-- 
Christopher Armstrong
<A HREF="http://radix.twistedmatrix.com/">http://radix.twistedmatrix.com/</A>
<A HREF="http://planet-if.com/">http://planet-if.com/</A>
-------------- next part --------------
An HTML attachment was scrubbed...
URL: &lt;/pipermail/twisted-python/attachments/20130618/6b680bb4/attachment-0002.html&gt;
</PRE>

<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message (by thread): <A HREF="059564.html">[Twisted-Python] If the errbacks of a canceled Deferred are called with error other than CancelledError, is this acceptable?
</A></li>
	<LI>Next message (by thread): <A HREF="059568.html">[Twisted-Python] If the errbacks of a canceled Deferred are	called with error other than CancelledError, is this acceptable?
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#59566">[ date ]</a>
              <a href="thread.html#59566">[ thread ]</a>
              <a href="subject.html#59566">[ subject ]</a>
              <a href="author.html#59566">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="https://twistedmatrix.com/cgi-bin/mailman/listinfo/twisted-python">More information about the Twisted-Python
mailing list</a><br>
</body></html>
