<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
 <HEAD>
   <TITLE> [Twisted-Python] If the errbacks of a canceled Deferred are	called with error other than CancelledError, is this acceptable?
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:twisted-python%40twistedmatrix.com?Subject=Re%3A%20%5BTwisted-Python%5D%20If%20the%20errbacks%20of%20a%20canceled%20Deferred%20are%0A%09called%20with%20error%20other%20than%20CancelledError%2C%20is%20this%20acceptable%3F&In-Reply-To=%3C87txkpkd2v.fsf%40hermes.hocat.ca%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <style type="text/css">
       pre {
           white-space: pre-wrap;       /* css-2.1, curent FF, Opera, Safari */
           }
   </style>
   <META http-equiv="Content-Type" content="text/html; charset=utf-8">
   <LINK REL="Previous"  HREF="059589.html">
   <LINK REL="Next"  HREF="059603.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[Twisted-Python] If the errbacks of a canceled Deferred are	called with error other than CancelledError, is this acceptable?</H1>
    <B>Tom Prince</B> 
    <A HREF="mailto:twisted-python%40twistedmatrix.com?Subject=Re%3A%20%5BTwisted-Python%5D%20If%20the%20errbacks%20of%20a%20canceled%20Deferred%20are%0A%09called%20with%20error%20other%20than%20CancelledError%2C%20is%20this%20acceptable%3F&In-Reply-To=%3C87txkpkd2v.fsf%40hermes.hocat.ca%3E"
       TITLE="[Twisted-Python] If the errbacks of a canceled Deferred are	called with error other than CancelledError, is this acceptable?">tom.prince at ualberta.net
       </A><BR>
    <I>Sat Jun 22 16:14:32 MDT 2013</I>
    <P><UL>
        <LI>Previous message (by thread): <A HREF="059589.html">[Twisted-Python] If the errbacks of a canceled Deferred are called with error other than CancelledError, is this acceptable?
</A></li>
        <LI>Next message (by thread): <A HREF="059603.html">[Twisted-Python] If the errbacks of a canceled Deferred are called with error other than CancelledError, is this acceptable?
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#59602">[ date ]</a>
              <a href="thread.html#59602">[ thread ]</a>
              <a href="subject.html#59602">[ subject ]</a>
              <a href="author.html#59602">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>Terry Jones &lt;<A HREF="https://twistedmatrix.com/cgi-bin/mailman/listinfo/twisted-python">terry at jon.es</A>&gt; writes:

&gt;<i> Based on JP's comment, I still think I'm missing something here.
</I>
The original subject of this thread? There was a question of what errorq

&gt;<i> The problem that I was originally trying to address by getting 'cancel'
</I>&gt;<i> into deferreds is that the control flow you mention gets totally stuck if a
</I>&gt;<i> deferred never fires for some reason (this was happening to me in talking
</I>&gt;<i> to the Twitter API).
</I>
.cancel as currently implemented addresses this, as calling cancel
causes the deferred to fire.

&gt;<i> This goes against the thinking that only the code that creates a deferred
</I>&gt;<i> can fire it.
</I>
To allow anything else would be to break the abstraction

    d = Deferred()
    return d
    ...
    d.callback(5)

vs.
    d = Deferred()
    d.addCallback(lambda x: x+1)
    return d
    ...
    d.callback(4)

There is currently no way of distinguishing these to code
snippets. Allowing other code to callback/errback the deferred
would cause different results in the two cases.

&gt;<i> As API writers, we're used to being in control: we don't think it's a
</I>&gt;<i> good idea if we create and return a deferred in a method and the code
</I>&gt;<i> we return the deferred to then fires it itself.
</I>
It isn't so much a matter of control, as of abstraction. It isn't
uncommon for a single deferred to be pass through several systems, with
each stage adding more callbacks, changing the value that the next stage
will see in the callbacks they add.

If the &quot;final&quot; consumer could fire the deferred with any value, it would
need to know about all the stagse (or at least the first one) to know
what kind of value to put in.

&gt;<i> But as app writers consuming deferreds from these APIs, we
</I>&gt;<i> want more control (I do, anyway).
</I>
Well, the consumer can't control the deferreds that it gets but, as your
code demonstrates, it is easy enough to create a new deferred that
behaves however the consumer wants. The fact that this isn't the same
object isn't signifiant, since the identity of deferreds isn't an
interesting thing.


&gt;<i> The ControllableDeferred2013 class I posted last night shows one
</I>&gt;<i> way.
</I>
One comment about the code you posted: There doesn't really seem to be a
need to create a sepearte class, that forwards
.addCallback/.addErrback. You can just create a regular deferred that is
hooked hooked up in the appropriate way. (It may make sense for the
stage that sets this up to have an object, but it shouldn't pass it
along, it should just pass a regular deferred on). There are a few
places that accept deferreds that depend on the object being an instance
of deferred, which your object isn't.

  Tom


</PRE>

<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message (by thread): <A HREF="059589.html">[Twisted-Python] If the errbacks of a canceled Deferred are called with error other than CancelledError, is this acceptable?
</A></li>
	<LI>Next message (by thread): <A HREF="059603.html">[Twisted-Python] If the errbacks of a canceled Deferred are called with error other than CancelledError, is this acceptable?
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#59602">[ date ]</a>
              <a href="thread.html#59602">[ thread ]</a>
              <a href="subject.html#59602">[ subject ]</a>
              <a href="author.html#59602">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="https://twistedmatrix.com/cgi-bin/mailman/listinfo/twisted-python">More information about the Twisted-Python
mailing list</a><br>
</body></html>
