<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [Twisted-Python] udp exception if connection reset by other peer
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:twisted-python%40twistedmatrix.com?Subject=%5BTwisted-Python%5D%20udp%20exception%20if%20connection%20reset%20by%20other%0A%20peer&In-Reply-To=01e401c31a60%2494e5da20%24ec47da50%40pat">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="004082.html">
   <LINK REL="Next"  HREF="004084.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[Twisted-Python] udp exception if connection reset by other peer</H1>
    <B>Itamar Shtull-Trauring</B> 
    <A HREF="mailto:twisted-python%40twistedmatrix.com?Subject=%5BTwisted-Python%5D%20udp%20exception%20if%20connection%20reset%20by%20other%0A%20peer&In-Reply-To=01e401c31a60%2494e5da20%24ec47da50%40pat"
       TITLE="[Twisted-Python] udp exception if connection reset by other peer">itamar at itamarst.org
       </A><BR>
    <I>Wed May 14 17:45:25 EDT 2003</I>
    <P><UL>
        <LI>Previous message: <A HREF="004082.html">[Twisted-Python] udp exception if connection reset by other peer
</A></li>
        <LI>Next message: <A HREF="004084.html">AW: [Twisted-Python] udp exception if connection reset by other peer
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#4083">[ date ]</a>
              <a href="thread.html#4083">[ thread ]</a>
              <a href="subject.html#4083">[ subject ]</a>
              <a href="author.html#4083">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>On Wed, 14 May 2003 23:34:16 +0200
&quot;p@&quot; &lt;<A HREF="http://twistedmatrix.com/cgi-bin/mailman/listinfo/twisted-python">digi at treepy.com</A>&gt; wrote:

&gt;<i> If i send a udp packet with a connected udp-protocoll to an other peer
</I>&gt;<i> where the port is closed or not reachable and the other peer resets
</I>&gt;<i> the connection I get an exception...
</I>
Good point. UDP does occasionally give information about non-reachable
hosts, currently expressed in Twisted by an exception. Should I bother
raising these or just swallow them silently?

Meanwhile, you can just wrap the write() with a try/except: pass.


-- 
Itamar Shtull-Trauring    <A HREF="http://itamarst.org/">http://itamarst.org/</A>
<A HREF="http://www.zoteca.com">http://www.zoteca.com</A> -- Python &amp; Twisted consulting


</PRE>

<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="004082.html">[Twisted-Python] udp exception if connection reset by other peer
</A></li>
	<LI>Next message: <A HREF="004084.html">AW: [Twisted-Python] udp exception if connection reset by other peer
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#4083">[ date ]</a>
              <a href="thread.html#4083">[ thread ]</a>
              <a href="subject.html#4083">[ subject ]</a>
              <a href="author.html#4083">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="http://twistedmatrix.com/cgi-bin/mailman/listinfo/twisted-python">More information about the Twisted-Python
mailing list</a><br>
</body></html>
