<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [Twisted-Python] Re: closing udp client? (p@)
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:twisted-python%40twistedmatrix.com?Subject=%5BTwisted-Python%5D%20Re%3A%20closing%20udp%20client%3F%20%28p%40%29&In-Reply-To=20030514045901.8790.34071.Mailman%40pyramid.twistedmatrix.com">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="004097.html">
   <LINK REL="Next"  HREF="004082.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[Twisted-Python] Re: closing udp client? (p@)</H1>
    <B>W.J.</B> 
    <A HREF="mailto:twisted-python%40twistedmatrix.com?Subject=%5BTwisted-Python%5D%20Re%3A%20closing%20udp%20client%3F%20%28p%40%29&In-Reply-To=20030514045901.8790.34071.Mailman%40pyramid.twistedmatrix.com"
       TITLE="[Twisted-Python] Re: closing udp client? (p@)">miathan at goliath.darktech.org
       </A><BR>
    <I>Wed May 14 08:29:03 EDT 2003</I>
    <P><UL>
        <LI>Previous message: <A HREF="004097.html">[Twisted-Python] a little OT: python workshop became a twisted	workshop
</A></li>
        <LI>Next message: <A HREF="004082.html">[Twisted-Python] udp exception if connection reset by other peer
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#4071">[ date ]</a>
              <a href="thread.html#4071">[ thread ]</a>
              <a href="subject.html#4071">[ subject ]</a>
              <a href="author.html#4071">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>&gt;<i> I want to send a udp packet and then wait for the answer. but what if
</I>&gt;<i> there is no answer? So I need a timeout client...
</I>&gt;<i>
</I>&gt;<i> I tried it with:
</I>&gt;<i>
</I>&lt;snip&gt;
&gt;<i>
</I>&gt;<i> this works. but if I try to close this protocol after 5 seconds with
</I>&gt;<i> self.transport.loseConnection() I get an exception..
</I>&gt;<i> So my actuall question is: how to close this port/protocol/factory
</I>&gt;<i> again?
</I>
The timeout is still armed when you lose the connection.

On connection, you do

self.egg = reactor.callLater(5, self.timeout())

When you deconstruct the thing again you do:

self.egg.cancel()

I don't know if this has anything to do with it, but be more
elaborate on which exception you get?

Wladimir



</PRE>

<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="004097.html">[Twisted-Python] a little OT: python workshop became a twisted	workshop
</A></li>
	<LI>Next message: <A HREF="004082.html">[Twisted-Python] udp exception if connection reset by other peer
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#4071">[ date ]</a>
              <a href="thread.html#4071">[ thread ]</a>
              <a href="subject.html#4071">[ subject ]</a>
              <a href="author.html#4071">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="http://twistedmatrix.com/cgi-bin/mailman/listinfo/twisted-python">More information about the Twisted-Python
mailing list</a><br>
</body></html>
