<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
 <HEAD>
   <TITLE> [Twisted-Python] socket is not closed when connection failed
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:twisted-python%40twistedmatrix.com?Subject=Re%3A%20%5BTwisted-Python%5D%20socket%20is%20not%20closed%20when%20connection%20failed&In-Reply-To=%3CPine.LNX.4.61.0502161529260.28462%40forty-thieves.cis.upenn.edu%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <style type="text/css">
       pre {
           white-space: pre-wrap;       /* css-2.1, curent FF, Opera, Safari */
           }
   </style>
   <META http-equiv="Content-Type" content="text/html; charset=utf-8">
   <LINK REL="Previous"  HREF="042094.html">
   <LINK REL="Next"  HREF="042096.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[Twisted-Python] socket is not closed when connection failed</H1>
    <B>Yun Mao</B> 
    <A HREF="mailto:twisted-python%40twistedmatrix.com?Subject=Re%3A%20%5BTwisted-Python%5D%20socket%20is%20not%20closed%20when%20connection%20failed&In-Reply-To=%3CPine.LNX.4.61.0502161529260.28462%40forty-thieves.cis.upenn.edu%3E"
       TITLE="[Twisted-Python] socket is not closed when connection failed">maoy at cis.upenn.edu
       </A><BR>
    <I>Wed Feb 16 13:35:15 MST 2005</I>
    <P><UL>
        <LI>Previous message (by thread): <A HREF="042094.html">[Twisted-Python] Delivery service mail
</A></li>
        <LI>Next message (by thread): <A HREF="042096.html">[Twisted-Python] socket is not closed when connection failed
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#42095">[ date ]</a>
              <a href="thread.html#42095">[ thread ]</a>
              <a href="subject.html#42095">[ subject ]</a>
              <a href="author.html#42095">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>Hi everyone,

   I found that if a TCP connection is failed, e.g. UserTimeout or No route 
to host, connection refused, etc, i.e. when factory.ConnectionFailed is 
called, the socket is not properly cleaned up. i.e. socket.close() wasn't 
called. In this case, when I try to connect to many unreachable hosts, my 
file descriptor will finally be gone.

Could someone confirm me on this?  Thanks. I'm using twisted 1.3.0rc1

Yun



</PRE>

<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message (by thread): <A HREF="042094.html">[Twisted-Python] Delivery service mail
</A></li>
	<LI>Next message (by thread): <A HREF="042096.html">[Twisted-Python] socket is not closed when connection failed
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#42095">[ date ]</a>
              <a href="thread.html#42095">[ thread ]</a>
              <a href="subject.html#42095">[ subject ]</a>
              <a href="author.html#42095">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="https://twistedmatrix.com/cgi-bin/mailman/listinfo/twisted-python">More information about the Twisted-Python
mailing list</a><br>
</body></html>
