<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [Twisted-Python] could plugin cache get currupted?
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:twisted-python%40twistedmatrix.com?Subject=%5BTwisted-Python%5D%20could%20plugin%20cache%20get%20currupted%3F&In-Reply-To=">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="017201.html">
   <LINK REL="Next"  HREF="017205.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[Twisted-Python] could plugin cache get currupted?</H1>
    <B>Gabriel Rossetti</B> 
    <A HREF="mailto:twisted-python%40twistedmatrix.com?Subject=%5BTwisted-Python%5D%20could%20plugin%20cache%20get%20currupted%3F&In-Reply-To="
       TITLE="[Twisted-Python] could plugin cache get currupted?">mailing_lists at evotex.ch
       </A><BR>
    <I>Thu Mar 27 12:30:11 EDT 2008</I>
    <P><UL>
        <LI>Previous message: <A HREF="017201.html">[Twisted-Python] Re: [ANN] Twisted 8.0
</A></li>
        <LI>Next message: <A HREF="017205.html">[Twisted-Python] could plugin cache get currupted?
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#17203">[ date ]</a>
              <a href="thread.html#17203">[ thread ]</a>
              <a href="subject.html#17203">[ subject ]</a>
              <a href="author.html#17203">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>Hello,

I coded a program that uses Twisted's plugin system. I have noticed that 
if I interrupt the application using Ctrl+C (SIGINT) that when I run it 
next time I get this :

  File &quot;/usr/lib/python2.5/site-packages/twisted/plugin.py&quot;, line 227, 
in getPlugins
    allDropins = getCache(package)
--- &lt;exception caught here&gt; ---
  File &quot;/usr/lib/python2.5/site-packages/twisted/plugin.py&quot;, line 178, 
in getCache
    provider = namedAny(module.__name__ + '.' + moduleName)
  File &quot;/usr/lib/python2.5/site-packages/twisted/python/reflect.py&quot;, 
line 375, in namedAny
    obj = getattr(obj, n)
exceptions.AttributeError: 'module' object has no attribute 'SendFile'

Could this mean that the plugin cache is corrupt? If so, How can I keep 
it from getting corrupted (is there a safe way of closing it)?

Thanks,
Gabriel


</PRE>

<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="017201.html">[Twisted-Python] Re: [ANN] Twisted 8.0
</A></li>
	<LI>Next message: <A HREF="017205.html">[Twisted-Python] could plugin cache get currupted?
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#17203">[ date ]</a>
              <a href="thread.html#17203">[ thread ]</a>
              <a href="subject.html#17203">[ subject ]</a>
              <a href="author.html#17203">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="http://twistedmatrix.com/cgi-bin/mailman/listinfo/twisted-python">More information about the Twisted-Python
mailing list</a><br>
</body></html>
