<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
 <HEAD>
   <TITLE> [Twisted-Python] @inlineCallbacks eat the traceback. Help?
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:twisted-python%40twistedmatrix.com?Subject=Re%3A%20%5BTwisted-Python%5D%20%40inlineCallbacks%20eat%20the%20traceback.%20Help%3F&In-Reply-To=%3Cfj4k31%2494a%241%40ger.gmane.org%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <style type="text/css">
       pre {
           white-space: pre-wrap;       /* css-2.1, curent FF, Opera, Safari */
           }
   </style>
   <META http-equiv="Content-Type" content="text/html; charset=utf-8">
   <LINK REL="Previous"  HREF="048922.html">
   <LINK REL="Next"  HREF="048925.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[Twisted-Python] @inlineCallbacks eat the traceback. Help?</H1>
    <B>Matthias Urlichs</B> 
    <A HREF="mailto:twisted-python%40twistedmatrix.com?Subject=Re%3A%20%5BTwisted-Python%5D%20%40inlineCallbacks%20eat%20the%20traceback.%20Help%3F&In-Reply-To=%3Cfj4k31%2494a%241%40ger.gmane.org%3E"
       TITLE="[Twisted-Python] @inlineCallbacks eat the traceback. Help?">matthias at urlichs.de
       </A><BR>
    <I>Tue Dec  4 15:24:33 MST 2007</I>
    <P><UL>
        <LI>Previous message (by thread): <A HREF="048922.html">[Twisted-Python] wx and twisted
</A></li>
        <LI>Next message (by thread): <A HREF="048925.html">[Twisted-Python] @inlineCallbacks eat the traceback. Help?
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#48924">[ date ]</a>
              <a href="thread.html#48924">[ thread ]</a>
              <a href="subject.html#48924">[ subject ]</a>
              <a href="author.html#48924">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>It seems that @inlineCallbacks trashes the error traceback when you yield
a Deferred that emits an error. That's not very social behavior.

Any ideas how to get the traceback back?

This is Twisted 2.5.

Traceback (most recent call last):
  File &quot;/usr/lib/python2.5/site-packages/twisted/python/context.py&quot;, line 37, in callWithContext
    return func(*args,**kw)
  File &quot;/usr/lib/python2.5/site-packages/twisted/internet/threads.py&quot;, line 25, in _putResultInDeferred
    result = f(*args, **kwargs)
  File &quot;/usr/lib/python2.5/site-packages/twisted/internet/defer.py&quot;, line 813, in unwindGenerator
    return _inlineCallbacks(None, f(*args, **kwargs), Deferred())
  File &quot;/usr/lib/python2.5/site-packages/twisted/internet/defer.py&quot;, line 724, in _inlineCallbacks
    result = g.throw(result.type, result.value, result.tb)
--- &lt;exception caught here&gt; ---
  File &quot;/var/lib/python-support/python2.5/homevent/worker.py&quot;, line 153, in _process
    r = yield w.process(event=self.event, queue=self)
exceptions.TypeError: float() argument must be a string or a number

-- 
Matthias Urlichs   |   {M:U} IT Design @ m-u-it.de   |  <A HREF="https://twistedmatrix.com/cgi-bin/mailman/listinfo/twisted-python">smurf at smurf.noris.de</A>
Disclaimer: The quote was selected randomly. Really. | <A HREF="http://smurf.noris.de">http://smurf.noris.de</A>
 - -
Know when to quit.



</PRE>

<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message (by thread): <A HREF="048922.html">[Twisted-Python] wx and twisted
</A></li>
	<LI>Next message (by thread): <A HREF="048925.html">[Twisted-Python] @inlineCallbacks eat the traceback. Help?
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#48924">[ date ]</a>
              <a href="thread.html#48924">[ thread ]</a>
              <a href="subject.html#48924">[ subject ]</a>
              <a href="author.html#48924">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="https://twistedmatrix.com/cgi-bin/mailman/listinfo/twisted-python">More information about the Twisted-Python
mailing list</a><br>
</body></html>
