<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
 <HEAD>
   <TITLE> [Twisted-Python] inlineCallbacks and current exceptions: leaky	abstraction or bug?
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:twisted-python%40twistedmatrix.com?Subject=Re%3A%20%5BTwisted-Python%5D%20inlineCallbacks%20and%20current%20exceptions%3A%20leaky%0A%09abstraction%20or%20bug%3F&In-Reply-To=%3C7E78305B-DDFC-40A6-B2B5-4BBCCEB7CA5B%40lvh.io%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <style type="text/css">
       pre {
           white-space: pre-wrap;       /* css-2.1, curent FF, Opera, Safari */
           }
   </style>
   <META http-equiv="Content-Type" content="text/html; charset=utf-8">
   
   
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[Twisted-Python] inlineCallbacks and current exceptions: leaky	abstraction or bug?</H1>
    <B>Laurens Van Houtven</B> 
    <A HREF="mailto:twisted-python%40twistedmatrix.com?Subject=Re%3A%20%5BTwisted-Python%5D%20inlineCallbacks%20and%20current%20exceptions%3A%20leaky%0A%09abstraction%20or%20bug%3F&In-Reply-To=%3C7E78305B-DDFC-40A6-B2B5-4BBCCEB7CA5B%40lvh.io%3E"
       TITLE="[Twisted-Python] inlineCallbacks and current exceptions: leaky	abstraction or bug?">_ at lvh.io
       </A><BR>
    <I>Mon Jul 28 02:54:54 MDT 2014</I>
    <P><UL>
        
        
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#61017">[ date ]</a>
              <a href="thread.html#61017">[ thread ]</a>
              <a href="subject.html#61017">[ subject ]</a>
              <a href="author.html#61017">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>Honored twistedeers,


Consider the following (blocking) decorator, which runs a function in a transaction:

def _with_transaction(f):
    def decorated(self, *args, **kwargs):
        conn = self.engine.connect()
        txn = conn.begin()

        try:
            result = f(self, conn, *args, **kwargs)
        except:
            txn.rollback()
            raise
        else:
            txn.commit()
            return

    return decorated

Where I to translate this logic verbatim to @inlineCallbacks, I get:

def _with_transaction(f):
    @inlineCallbacks
    def decorated(self, *args, **kwargs):
        conn = yield self.engine.connect()
        txn = yield conn.begin()

        try:
            result = yield f(self, conn, *args, **kwargs)
        except:
            yield txn.rollback()
            raise
        else:
            yield txn.commit()
            returnValue(result)

    return decorated

However, there’s a bug here! In the except clause: there’s an (implicit) current exception, to be re-raised by the bare raise statement. Unfortunately, when doing yield txn.rollback(), that conveniently eats said exception.

Of course, there’s a fairly simple workaround involving catching BaseException and capturing the exception instance explicitly.

I’m wondering if this is just a leaky abstraction, or if I should report it as a bug in @inlineCallbacks?


cheers
lvh



-------------- next part --------------
An HTML attachment was scrubbed...
URL: &lt;/pipermail/twisted-python/attachments/20140728/0e78902c/attachment-0002.html&gt;
-------------- next part --------------
A non-text attachment was scrubbed...
Name: signature.asc
Type: application/pgp-signature
Size: 841 bytes
Desc: Message signed with OpenPGP using GPGMail
URL: &lt;/pipermail/twisted-python/attachments/20140728/0e78902c/attachment.sig&gt;
</PRE>
<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	
	
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#61017">[ date ]</a>
              <a href="thread.html#61017">[ thread ]</a>
              <a href="subject.html#61017">[ subject ]</a>
              <a href="author.html#61017">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="https://twistedmatrix.com/cgi-bin/mailman/listinfo/twisted-python">More information about the Twisted-Python
mailing list</a><br>
</body></html>
